---
title: "COMPAR - Informal care"
author: "Irene Santi"
date: "23-07-2020"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 3
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '3'
---


```{r setup, include = FALSE}
#Open library
library(effects)
library(gmodels)
library(lme4)

#set working directory#
#setwd("C:/COMPAR/Analysis/R")

setwd("C:/Users/Isaac/Dropbox/COMPAR")

#open dataset#
#IC<-read.csv("C:/COMPAR/Saskia.csv")
IC <- read.csv("Saskia.csv")

```

```{r mixed model}
#Run mixed model#
informal_care_pred <- glmer(formula = inf_care ~ factor(gender) + scale(age) + heartattack_new2 + 
                              stroke_new2 + CKD_new2 + (1 | mergeid), data = IC, family = binomial)
```                              


## Mixed model (all countries)
                         

```{r}
informal_care_pred
```

```{r specialOptions,  include = FALSE}
#create dummy variables for country: Greece, Germany, Netherlands, Spain#
IC$Country<-substr(IC$mergeid,1,2)
table(IC$Country)
IC$GR <- ifelse(IC$Country == 'GR', 1, 0)
IC$DE <- ifelse(IC$Country == 'DE', 1, 0)
IC$NL <- ifelse(IC$Country == 'NL', 1, 0)
IC$ES <- ifelse(IC$Country == 'ES', 1, 0)

#Check
#CrossTable(IC$Country, IC$GR)
```

```{r models}
#Country specific regression model#

#Germany
informal_care_pred_DE <- glmer(formula = inf_care ~ factor(gender) + scale(age) + heartattack_new2 + 
                              stroke_new2 + CKD_new2 + DE + (1 | mergeid), data = IC, family = binomial)
```

```{r}
#Greece
informal_care_pred_GR <- glmer(formula = inf_care ~ factor(gender) + scale(age) + heartattack_new2 + 
                            stroke_new2 + CKD_new2 + GR + (1 | mergeid), data = IC, family = binomial)   
#Spain
informal_care_pred_ES <- glmer(formula = inf_care ~ factor(gender) + scale(age) + heartattack_new2 + 
                              stroke_new2 + CKD_new2 + ES + (1 | mergeid), data = IC, family = binomial)                              
```

```{r}
#The Netherlands
informal_care_pred_NL <- glmer(formula = inf_care ~ factor(gender) + scale(age) + heartattack_new2 + 
                              stroke_new2 + CKD_new2 + NL + (1 | mergeid), data = IC, family = binomial)
```


## Country-specific mixed models


### Germany
```{r}
                          
informal_care_pred_DE
```

### Greece
```{r}
informal_care_pred_GR
```

### Spain
```{r}
informal_care_pred_ES
```

### The Netherlands
```{r}
summary(informal_care_pred_NL)
```
                              

                              
                              
                              
                             